### ISSUE TITLE
Problem running on 5.4

### ISSUE THREAD

**Issue by NoakPalander** [fosspill/FFXIV_Modding_Tool#229]
No matter what I run, except "ffmt setup", I receive the same problem
```
Validating cache...
Checking backups before proceeding...
ERROR: One or more index files could not be found in <path to backup>. Creating new ones or downloading them from the TexTools discord is recommended
```
Running the version command yields:
ffmt 0.9.7.0
Game version 2020.12.2.0, as for the OS it's arch 5.9.9

**Comment by shinnova** [comment]
I'm curious, did you remember to reset your game before letting the game update? You can try placing [these](https://github.com/fosspill/FFXIV_Modding_Tool/files/5661273/5.4-Indexes.zip) in your backup directory and then running `ffmt problemcheck`

**Comment by NoakPalander** [comment]
No I did not, however the game runs fine it's just that no modpacks are willing to import. I'll try running the copying the indices and see how that'll do.

**Comment by lillelilje** [comment]
If you update the game without resetting you *will* break stuff unless you are super lucky (Or rather, if the update doesn't require a reset - which is pretty rare). FFMT and Textools for that matter, will not let you import unless you have valid - clean - backups. So, this is expected behavior. 
Maybe we should consider giving you the option of ignoring the issue, but that would just cause more problems in the end.

Did the clean indexes fix it?

**Comment by NoakPalander** [comment]
Yeah that made it work. Just unpacked the dir and removed the compressed folder. Afterwards both problemcheck and imports ran fine and it added the mods. Having a `--force` option that'd issue a warning could be good idea.

**Comment by lillelilje** [comment]
That's great news! Glad it fixed it.

Don't think we'll add a --force option as it would just cause issues in the long run. It's better that you are forced to fix your indexes to keep going.
